name: Docs

on: [push, pull_request]

jobs:

  DocLint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: anishathalye/proof-html@v1
        with:
          directory: ./docs
          check_favicon: false
          enforce_https: false
          url_ignore: |
            http://www.fabricadigital.com.br
            http://www.saxproject.org/
          url_ignore_re: |
            ^http://files.luaforge.net/
            ^https://opensource.org/
